import 'package:patient_app/features/records/domain/entities/record.dart';

class TestRecord {
  final String title;
  final String type;
  final DateTime date;
  final String content; // Using content instead of text to match JSON schema
  final String spaceId;
  final int viewCount;
  final List<String> tags;

  TestRecord({
    required this.title,
    required this.type,
    required this.date,
    required this.content,
    required this.spaceId,
    required this.viewCount,
    required this.tags,
  });

  factory TestRecord.fromJson(Map<String, dynamic> json) {
    return TestRecord(
      title: json['title'] as String? ?? '',
      type: json['type'] as String? ?? 'general',
      date: json['date'] != null
          ? DateTime.parse(json['date'] as String)
          : DateTime.now(),
      content: json['content'] as String? ?? '',
      spaceId: json['spaceId'] as String? ?? 'health',
      viewCount: json['viewCount'] as int? ?? 0,
      tags:
          (json['tags'] as List<dynamic>?)
              ?.map((tag) => tag.toString())
              .toList() ??
          [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'type': type,
      'date': date.toIso8601String(),
      'content': content,
      'spaceId': spaceId,
      'viewCount': viewCount,
      'tags': tags,
    };
  }

  // Convert to app's Record model
  RecordEntity toRecord() {
    return RecordEntity(
      id: null, // Will be generated by Isar
      spaceId: spaceId,
      type: type,
      date: date,
      title: title,
      text: content,
      tags: tags,
      viewCount: viewCount,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
  }

  // Create from app's Record model
  factory TestRecord.fromRecord(RecordEntity record) {
    return TestRecord(
      title: record.title,
      type: record.type,
      date: record.date,
      content: record.text ?? '',
      spaceId: record.spaceId,
      viewCount: record.viewCount,
      tags: record.tags.toList(),
    );
  }
}
